const userResolver = require("./user"),
  articleResolver = require("./article"),
  followerResolver = require("./follower"),
  blockUsersResolver = require("./blockUser"),
  videoResolver = require("./video"),
  commentResolver = require("./comment"),
  sessionResolver = require("./session"),
  reportResolver = require("./report"),
  galleryResolver = require("./gallery"),
  aduserResolver = require("./aduser"),
  compaignResolver = require("./compaign"),
  analyticsResolver = require("./analytics"),
  notificationsResolver = require("./notifications"),
  subscriptionResolver = require("./subscription"),
  subscribeUserResolver = require("./subscribeUser"),
  profileRatingResolver = require("./profileRating");

module.exports = {
  ...userResolver,
  ...articleResolver,
  ...followerResolver,
  ...blockUsersResolver,
  ...videoResolver,
  ...commentResolver,
  ...sessionResolver,
  ...reportResolver,
  ...galleryResolver,
  ...aduserResolver,
  ...compaignResolver,
  ...analyticsResolver,
  ...profileRatingResolver,
  ...subscribeUserResolver,
  ...subscriptionResolver,
  ...notificationsResolver,
};
